name: Generate sitemap

on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 12 * * 1'   # Mondays 06:00 MT
  workflow_dispatch:       # manual run

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: sitemap-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install sitemap generator
        run: npm i -g sitemap-generator-cli

      - name: Generate sitemap
        run: |
          sitemap-generator https://www.carsandcollectibles.com \
            -o sitemap.xml \
            --strip-querystring \
            --max-entries-per-file 45000 \
            --timeout 20000

      - name: Commit sitemap
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "Update sitemap" || echo "No changes to commit"
          git push
