name: Update Jalopy Inventory CSVs

on:
  schedule:
    - cron: '0 7 * * *'  # 1:00 AM Mountain Time (Daylight Saving Time)
  workflow_dispatch:       # Allow manual trigger from GitHub UI

jobs:
  update-inventory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run inventory script
        run: |
          python "jalopy-jungle/scripts/jalopy_scraper.py"

      - name: Move CSVs into inventory-csvs folder
        run: |
          mkdir -p "jalopy-jungle/inventory-csvs"
          mv *.csv "jalopy-jungle/inventory-csvs/"

      - name: Commit and push updated CSVs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add "jalopy-jungle/inventory-csvs/*.csv"
          git commit -m "Update all CSVs from GitHub Actions" || echo "No changes to commit"
          git push