name: Jalopy Jungle Inventory Scraper

on:
  schedule:
    - cron: '0 7 * * *' # 1:00 AM MT = 7:00 AM UTC
  workflow_dispatch:

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run scraping script
        run: |
          python jalopy-jungle/scripts/jalopy_scraper.py

      - name: Generate index.json
        run: |
          cd jalopy-jungle/inventory-csvs
          ls *.csv | jq -R -s -c 'split("\n")[:-1]' > index.json

      - name: Commit and push CSVs and index
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add -A
          git commit -m "Update inventory CSVs and index"
          git push
