name: Scrape Nampa eBay Sales

on:
  schedule:
    - cron: '30 8 * * *'
  workflow_dispatch:

jobs:
  scrape-nampa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with: { python-version: '3.x' }

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4

      - name: Scrape Nampa
        run: |
          python jalopy-jungle/scripts/ebay_scraper_nampa.py

      - name: Commit Nampa CSV
        run: |
          cd jalopy-jungle/ebay-sales
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add inventory_nampa_*ebay_sales_*.csv
          git commit -m "Update Nampa eBay sales CSV" || echo "No changes"
          git push
