name: Scrape Boise eBay Sales

on:
  schedule:
    - cron: '30 11 * * *'
  workflow_dispatch:

jobs:
  scrape-boise:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4

      - name: Scrape Boise
        run: |
          python jalopy-jungle/scripts/ebay_scraper_boise.py

      - name: Commit Boise CSV
        run: |
          cd jalopy-jungle/ebay-sales
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git pull origin master --rebase
          git add inventory_boise_*ebay_sales_*.csv
          git commit -m "Update Boise eBay sales CSV" || echo "No changes"
          git push
