name: Send Vehicle Alerts

on:
  schedule:
    - cron: '0 13 * * *'  # Runs daily at 7am MT (13:00 UTC)
  workflow_dispatch:      # Allows manual runs too

jobs:
  run-alerts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install PyGithub requests

      - name: Run alert script
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python jalopy-jungle/scripts/vehicle_alerts.py
